---

- name: ISECL - SGX QUOTE VERIFICATION SERVICE | Copy SQVS installer binary
  copy:
    src: "{{sqvs_installer_file_src}}"
    dest: "/root/{{sqvs_installer_name}}"
    mode: "u+x"

- name: ISECL - SGX QUOTE VERIFICATION SERVICE | Copy trusted_rootca.pem
  copy:
    src: "{{sqvs_trusted_rootca_file_src}}"
    dest: "/tmp/{{sqvs_trusted_rootca_filename}}"
    mode: "u+x"

- name: ISECL - SGX QUOTE VERIFICATION SERVICE | Generate sqvs.env file
  template:
    src: "sqvs.env.j2"
    dest: "/root/sqvs.env"
    mode: "u+x"

- name: ISECL - SGX QUOTE VERIFICATION SERVICE | Install SGX Quote Verification Service
  shell: "set -o pipefail && ./{{ sqvs_installer_name }} 2>&1 | tee sgx_quote_verification_service-install.log"
  register: sqvs_install_log
  args:
    chdir: /root
    executable: /bin/bash
    creates: /opt/sqvs/bin/sqvs
  notify: start sqvs    

- meta: flush_handlers

- name: ISECL - SGX QUOTE VERIFICATION SERVICE | Verify successful installation of SQVS
  shell: grep 'Installation completed successfully!' /root/sgx_quote_verification_service-install.log
  register: successful_install
  failed_when: "'Installation completed successfully!' not in successful_install.stdout"
