---
- name: INSTALL DOCKER | Install docker repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    chdir: /root
    executable: /bin/bash

- name: INSTALL DOCKER | Install docker
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - "docker-ce-{{docker_version}}"
  notify: start docker

- meta: flush_handlers
