---

- name: ISECL - SGX HOST VERIFICATION SERVICE | Copy SHVS installer binary
  copy:
    src: "{{shvs_installer_file_src}}"
    dest: "/root/{{shvs_installer_name}}"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Copy aas-util_user-role.sh file
  copy:
    src: "{{binaries_path}}/aas-util_user-role.sh"
    dest: "/root/aas-util_user-role.sh"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Copy default_roles.conf file
  template:
    src: "shvs_users_roles_installation.conf.j2"
    dest: "/root/shvs_users_roles.conf"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Execute aas-util_user-role.sh
  shell: "./aas-util_user-role.sh -ru -c shvs_users_roles.conf"
  args:
    chdir: /root
    executable: /bin/bash

- name: ISECL - SGX HOST VERIFICATION SERVICE | Create token for SHVS user
  uri:
    url: "https://{{aas}}:{{aas_port}}/aas/token"
    body_format: json
    body:
       {
       "username": "{{shvs_admin_username}}",
       "password": "{{shvs_admin_password}}"
       }
    method: POST
    use_proxy: no
    validate_certs: no
    return_content: yes
  register: shvs_bootstrap_token

- name: ISECL - SGX HOST VERIFICATION SERVICE | Generate shvs.env file
  template:
    src: "shvs.env.j2"
    dest: "/root/shvs.env"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Install SGX Host Verification Service
  shell: "set -o pipefail && ./{{ shvs_installer_name }} 2>&1 | tee sgx_host_verification_service-install.log"
  register: shvs_install_log
  args:
    chdir: /root
    executable: /bin/bash
    creates: /opt/shvs/bin/shvs
  notify: start shvs

- meta: flush_handlers

- name: ISECL - SGX HOST VERIFICATION SERVICE | Verify successful installation of SHVS
  shell: grep 'Installation completed successfully!' /root/sgx_host_verification_service-install.log
  register: successful_install
  failed_when: "'Installation completed successfully!' not in successful_install.stdout"