---
 
- name: ISECL - SGX CACHING SERVICE | Copy SCS installer binary
  copy:
    src: "{{scs_installer_file_src}}"
    dest: "/root/{{scs_installer_name}}"
    mode: "u+x"

- name: ISECL - SGX CACHING SERVICE | Generate scs.env file
  template:
    src: "scs.env.j2"
    dest: "/root/scs.env"
    mode: "u+x"

- name: ISECL - SGX CACHING SERVICE | Install SGX Caching Service
  shell: "set -o pipefail && ./{{ scs_installer_name }} 2>&1 | tee sgx_caching_service-install.log"  
  register: scs_install_log  
  args:
    chdir: /root
    executable: /bin/bash
    creates: /opt/scs/bin/scs
  notify: start scs    

- meta: flush_handlers

- name: ISECL - SGX CACHING SERVICE | Verify successful installation of SCS
  shell: grep 'Installation completed successfully!' /root/sgx_caching_service-install.log
  register: successful_install
  failed_when: "'Installation completed successfully!' not in successful_install.stdout"
