---
- name: ISECL - INTEGRATION HUB | Copy aas-util_user-role.sh file
  copy:
    src: "{{binaries_path}}/aas-util_user-role.sh"
    dest: "/root/aas-util_user-role.sh"
    mode: "u+x"
  when: setup == 'sgx-attestation-kubernetes' or setup == 'sgx-orchestration-kubernetes' or 'sgx-attestation-openstack' or setup == 'sgx-orchestration-openstack'

- name: ISECL - INTEGRATION HUB | Copy scs_users_roles.conf file
  template:
    src: "ihub_users_roles_installation.conf.j2"
    dest: "/root/ihub_users_roles.conf"
    mode: "u+x"
  when: setup == 'sgx-attestation-kubernetes' or setup == 'sgx-orchestration-kubernetes' or 'sgx-attestation-openstack' or setup == 'sgx-orchestration-openstack'

- name: ISECL - INTEGRATION HUB | Execute aas-util_user-role.sh
  shell: "bash -x aas-util_user-role.sh -ru -c ihub_users_roles.conf"
  args:
    chdir: /root
    executable: /bin/bash
  when: setup == 'sgx-attestation-kubernetes' or setup == 'sgx-orchestration-kubernetes' or 'sgx-attestation-openstack' or setup == 'sgx-orchestration-openstack'

- name: ISECL - INTEGRATION HUB | Create token for IHUB user
  uri:
    url: "https://{{aas}}:{{aas_port}}/aas/token"
    body_format: json
    body:
       {
       "username": "{{ihub_service_username}}",
       "password": "{{ihub_service_password}}"
       }
    method: POST
    use_proxy: no
    validate_certs: no
    return_content: yes
  register: ihub_bootstrap_token
  when: setup == 'sgx-attestation-kubernetes' or setup == 'sgx-orchestration-kubernetes' or 'sgx-attestation-openstack' or setup == 'sgx-orchestration-openstack'

- name: ISECL - INTEGRATION HUB | Generate ihub.env file
  template:
    src: ihub.env.j2
    dest: /root/ihub.env

- name: ISECL - INTEGRATION HUB | COPYING IHUB binary installer
  copy:
    src: "{{ ihub_installer_file_src }}"
    dest: "/root/{{ ihub_installer_file_name }}"
    mode: "u+x"
