---

- name: ISECL - SGX HOST VERIFICATION SERVICE | Copy SHVS installer binary
  copy:
    src: "{{shvs_installer_file_src}}"
    dest: "/root/{{shvs_installer_name}}"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Generate shvs.env file
  template:
    src: "shvs.env.j2"
    dest: "/root/shvs.env"
    mode: "u+x"

- name: ISECL - SGX HOST VERIFICATION SERVICE | Install SGX Host Verification Service
  shell: "set -o pipefail && ./{{ shvs_installer_name }} 2>&1 | tee sgx_host_verification_service-install.log"
  register: shvs_install_log
  args:
    chdir: /root
    executable: /bin/bash
    creates: /opt/shvs/bin/shvs
  notify: start shvs

- meta: flush_handlers

- name: ISECL - SGX HOST VERIFICATION SERVICE | Verify successful installation of SHVS
  shell: grep 'Installation completed successfully!' /root/sgx_host_verification_service-install.log
  register: successful_install
  failed_when: "'Installation completed successfully!' not in successful_install.stdout"