---
- name: ISECL - SGX DEPENDENCIES | Create tmp directory
  file:
    path: "/tmp/{{sgxdep_installer_file__name}}"
    state: directory   

- name: ISECL - SGX DEPENDENCIES | Copy tar bundle and other files
  copy: 
    src: "{{sgxdep_installer_file_src}}/"
    dest: "/tmp/{{sgxdep_installer_file__name}}"
    mode: "u+x"

- name: ISECL - SGX DEPEPNDENCIES | Untar the tar bundle
  shell: bash -x skclib_untar.sh
  args:
    chdir: /tmp/{{sgxdep_installer_file__name}}

- name: ISECL - SGX DEPENDENCIES | Deploy SGX DEPENDENCIES
  shell: "set -o pipefail && ./deploy_sgx_dependencies.sh 2>&1 | tee /root/sgx-dependencies-installer.log"  
  args:
    chdir: /tmp/{{sgxdep_installer_file__name}}
