---
- name: INSTALL CRIO | RHEL - Add crio repo
  shell: dnf config-manager --add-repo {{item}}
  args:
    chdir: /root
    executable: /bin/bash
    creates: 
      - /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}.repo
      - /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    warn: false
  with_items: 
      - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{crio_os}}/devel:kubic:libcontainers:stable.repo
      - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}/{{crio_os}}/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}.repo
  
- name: INSTALL CRIO | Install cri-o runtime  
  dnf: 
    name: cri-o
    state: present
    update_cache: yes