---
- name: ISECL - KEY BROKER SERVICE | Copying aas-util_user-role.sh
  copy:
    src: "{{binaries_path}}/aas-util_user-role.sh"
    dest: "/root/aas-util_user-role.sh"
    mode: "u+x"
    
- name: ISECL - KEY BROKER SERVICE | Copying default_roles.conf
  template:
    src: "skms_user_roles.conf.j2"
    dest: "/root/skms_user_roles.conf"
    mode: "u+x"

- name: ISECL - KEY BROKER SERVICE | Copying aas-util_user-role.sh
  shell: "bash -x aas-util_user-role.sh -ru -c skms_user_roles.conf"  
  args:
    chdir: /root
    executable: /bin/bash 

- name: ISECL - KEY BROKER SERVICE | Create token for SKMS user
  uri:
    url: "https://{{aas}}:{{aas_port}}/aas/token"
    body_format: json
    body:
       {
       "username": "{{skbs_admin_username}}",
       "password": "{{skbs_admin_password}}"
       }
    method: POST
    use_proxy: no
    validate_certs: no
    return_content: yes
  register: setup_admin_token

- name: ISECL - KEY BROKER SERVICE | Generate kms.env file
  template:
    src: skms.env.j2
    dest: /root/kms.env


- name: ISECL - KEY BROKER SERVICE | Copy KBS binary installler
  copy:
    src: "{{ skbs_installer_file_src }}"
    dest: "/root/{{ skbs_installer_name }}"
    mode: "u+x"

- name: ISECL - KEY BROKER SERVICE | Install Key Broker Service
  shell: "set -o pipefail && ./{{ skbs_installer_name }} 2>&1 | tee skey_broker_service-install.log"
  args:
    chdir: /root
    executable: /bin/bash
    creates: /opt/skms/bin/skms
  notify: start skms

- meta: flush_handlers

- name: ISECL - KEY BROKER SERVICE | Verify successful installation of KBS
  shell: grep 'Error' /root/skey_broker_service-install.log
  register: successful_install
  failed_when: "'Error' in successful_install.stdout"