---
- name: ISECL - SAMPLE APPS | Create installation directory
  file:
    path: "/root/{{sampleapps_installer_name}}"
    state: directory

- name: ISECL - SAMPLE APPS | Copy tar bundle and other files
  copy:
    src: "{{sampleapps_installer_file_src}}/{{item}}"
    dest: "/root/{{sampleapps_installer_name}}"
    mode: "u+x"
  loop:
    - sample_apps.tar
    - sample_apps.sha2
    - sampleapps_untar.sh

- name: ISECL - SAMPLE APPS | Untar the tar bundle
  shell: bash -x sampleapps_untar.sh
  args:
    chdir: /root/{{sampleapps_installer_name}}

- name: ISECL - SAMPLE APPS | Deploy SGX Dependencies
  shell: "set -o pipefail && ./deploy_sgx_dependencies.sh 2>&1 | tee /root/sgx-dependencies-installer.log"
  args:
    chdir: /root/{{sampleapps_installer_name}}
    executable: /bin/bash
