---
- name: ISECL - POPULATE USERS | Generate populate-users.env file
  template:
    src: "populate-users.env.j2"
    dest: "/root/populate-users.env"


- name: ISECL - POPULATE USERS | Copy populate-users script
  copy:
    src: "{{ populate_users_script_file_src }}"
    dest: /root/populate-users.sh
    mode: "u+x"


- name: ISECL - POPULATE USERS | Run populate-users script
  raw: "set -o pipefail && ./populate-users.sh 2>&1 | tee populate_users.log"

- name: ISECL - POPULATE USERS | Get token for install admin user
  shell: "set -o pipefail && cat populate_users.log | grep -m 1 \"BEARER_TOKEN\" | cut -d \"=\" -f2"
  args:
    chdir: /root
    executable: /bin/bash
  register: admin_token


- name: ISECL - POPULATE USERS | Set required facts to remote machines
  set_fact:
    setup_admin_token: "{{ admin_token.stdout }}"
  delegate_to: "{{ host }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host
